export const profileForm = [
  {
    id: 1,
    type: "dropDown",
    label: "Organization type",
    name: "organization-type",
    required: true,
    value: "",
    options: ["Medical Store", "Grocery Store", "Agriculture Store"],
  },
  {
    id: 2,
    type: "textField",
    label: "Organization Name",
    name: "organization-name",
    required: true,
    value: "",
  },
  {
    id: 3,
    type: "textField",
    label: "Owner First Name",
    name: "owner-firstName",
    required: true,
    value: "",
  },
  {
    id: 4,
    type: "textField",
    label: "Owner Last Name",
    name: "owner-lastName",
    required: true,
    value: "",
  },
  {
    id: 5,
    type: "textField",
    label: "Mobile Number",
    name: "mobile-number",
    required: true,
    value: "",
  },
  {
    id: 6,
    type: "textField",
    label: "Email Address",
    name: "email-address",
    value: "",
  },
  {
    id: 7,
    type: "textField",
    label: "GST Number",
    name: "gst-number",
    value: "",
  },
   
  {
    id: 8,
    type: "textField",
    label: "Password",
    name: "password",
    isMask:true,
    value: "",
  },
];
